version: '3.8'

services:
  service1:
    image: kafka-producer:v1
    ports:
      - "8080:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - spring-net

  service2:
    image: kafka-consumer:v1
    ports:
      - "8080:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - spring-net

networks:
  spring-net:
    driver: bridge
