spring:
  application:
    name: kafka-consumer
  kafka:
    consumer:
      group-id: user-message-consumer #keeping it empty because I don't have a group, kafka will automatically assign one, can be removed as well
      enable-auto-commit: true
      auto-commit-interval: 1000
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      #bootstrap-servers: 172.17.0.2:9092 # Find of container: docker inspect <container_id_or_name> | grep IPAddress
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      
server:
  port: 8082

message:
  shceduler:
    cron: 10000 #2*60*1000
  kafka:
    consumer:
      topic: message

logging:
  level:
    root: INFO
#  file:
 #   name: logs/app.log
  #  max-size: 10MB
   # max-history: 30
